settings:
  subscription:
    name: "SEC-Blue"
    id: "xxxxxxxx-xxxx-xxxx-xxxx-xxxxxxxxxxxx"
    tenantId: "xxxxxxxx-xxxx-xxxx-xxxx-xxxxxxxxxxxx"
  maintenance:
    start_day: 28
    end_day: 31
    start_time: "00:00"
    end_time: "05:00"
  permissions:
    hasAccess: ['<username>']